### ISSUE TITLE
Curse effect doesnt apply until I deselect and then reselect the token.

### ISSUE THREAD

**Issue by ourotech** [Wigsinator/betterCurses#14] opened 2021-05-19 18:18 UTC
Hi, having an issue where the "better curses" effect doesn't get applied to the casting token until I either untarget and retarget the target token, or until I deselect and reselect the casting token. 
I'm wondering if you've encountered this issue or if it's intended behaviour or maybe I've just messed something up with the setup? 
I do have a lot of modules installed so I'm just running a quick sanity check before I spend hours debugging.

Thanks in advance!

**Comment by Wigsinator** [comment] 2021-05-19 18:23
I can confirm that that is not intended behaviour. If there is just one target, the active effect on the caster should be applied when the curse function is used. If you are willing to do a bit of digging, I would start by putting breakpoints in the curse.js file, if you know how. If not, I'd be happy to take a look later.

**Comment by ourotech** [comment] 2021-05-19 18:38
Ahhh! I hadn't even thought about using break points, still fairly new to foundry and node in general. 

Right so I think the issue is on line 13, user.targets.length is undefined for me, even though user.targets has a token within it, here's a screenshot of the results of both within the console at the breakpoint, any ideas?
![debug](https://user-images.githubusercontent.com/67447915/118866159-a1638500-b8d9-11eb-93df-2e47c254255c.jpg)

**Comment by Wigsinator** [comment] 2021-05-19 18:47
I did a quick google search, and from what I can tell, sets don't use length, they instead use size. It should be a pretty easy fix on my end. For right now, the work around works, so I'm going to ask you to deal with that, but I should have a patch out by week's end.

**Comment by ourotech** [comment] 2021-05-19 18:56
Awesome stuff, yeah I've just changed user.targets.length to user.targets.size and it works as intended now, thanks for your help! 

So is user.targets not supposed to be a 'set' in a vanilla installation of foundry?

**Comment by Wigsinator** [comment] 2021-05-19 19:03
It being a set is vanilla foundry, I'm just an idiot who didn't look up the distinctions because length worked. In all likelihood, it broke due to a browser update deprecating the use of set.length.  It just forces me to do it right.

**Comment by ourotech** [comment] 2021-05-19 19:09
Ahh, no worries bud, at least it's a simple fix. Thank you for the quick replies too. 

I'm not sure of the procedure with closing tickets, if you need me to close the ticket just let me know, or if you want to wait till you've put out the patch or something.

**Comment by Wigsinator** [comment] 2021-05-19 19:10
I prefer to keep the issue open until the patch is released, I'll handle closing it.

Thank you for the detailed information that let me diagnose it easily!

**Comment by Wigsinator** [comment] 2021-06-03 04:58
Solved in release 3.0.0

**Closed as completed by Wigsinator** 2021-06-03 04:58 UTC
Labels: bug
