### ISSUE TITLE
After adding a curse, get curseName not defined

### ISSUE THREAD

**Issue by Wigginns** [Wigsinator/betterCurses#12] opened 2021-05-07 20:11 UTC
Attempted to add favoredFoe to ranger alternate ability favored foe:

![image](https://user-images.githubusercontent.com/3180645/117503137-c5b87c80-af3d-11eb-891c-38a699b2aca3.png)

And then attempted to call it in macro as described in readme

![image](https://user-images.githubusercontent.com/3180645/117503272-f3052a80-af3d-11eb-8b83-2dca154c5541.png)

I am very new to Foundry and I wasn't sure if the name needed brackets or not but neither option worked. It's somewhat likely I'm calling this all wrong and need to take a different approach. 

console shows: `ReferenceError: favoredFoe is not defined
    at Macro.eval (eval at callScriptMacroFunction (Macros.js:176), `

**Comment by Wigsinator** [comment] 2021-05-07 20:18
Alright, I immediately see what the problem is. Instead of the brackets, make the command in the macro `BetterCurses.curse("favoredFoe")`.
The quotation marks tell foundry to treat the text "favoredFoe" as a string, rather than a variable.

Welcome to Foundry! If you have any other questions, I'd be glad to help you out. For now, I'm going to close this issue, but if the issue persists, feel free to re-open it.

**Closed as completed by Wigsinator** 2021-05-07 20:18 UTC
Labels: troubleshooting

**Comment by Wigginns** [comment] 2021-05-07 20:47
Perfect! I know enough JS I should have been able to figure this out but apparently my brain is fried. Thanks!

Just a small suggestion that the readme include an example with the correct formatting to help other noobies :)
